export enum MessagePatternEnum {
  CREATE_REPORT = 'CREATE_REPORT',
  GET_REPORT = 'GET_REPORT',
  GRI_DISCLOSURES = 'GRI_DISCLOSURES',
  HKEX_DISCLOSURES = 'HKEX_DISCLOSURES',
  WEF_DISCLOSURES = 'WEF_DISCLOSURES',
  SASB_DISCLOSURES = 'SASB_DISCLOSURES',
}
