version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    container_name: microservice-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: microservice-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: 'microservice-dev-custom-framework-uom-upload:1:1'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    container_name: microservice-postgres
    image: postgres:11.8-alpine
    expose:
      - "5432"
    ports:
    - "5432:5432"
    volumes:
    - data-volume:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservice
    networks:
    - postgres
volumes:
  data-volume:
networks:
  postgres:
    driver: bridge
